apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-eks
  region: eu-west-1

vpc:
  subnets:
    private:
      eu-west-1a: { id: subnet-0e2237277fdc6641f }
      eu-west-1b: { id: subnet-06364fe4153d1b22b }
      eu-west-1a: { id: subnet-0bfd63e6df03ddca1 }
      eu-west-1b: { id: subnet-0735cc35ff5b785f8 }

nodeGroups:
  - name: ng-worker
    labels: { role: workers }
    instanceType: t3.large
    desiredCapacity: 2
    privateNetworking: true
  - name: ng-2-builder
    labels: { role: builders }
    instanceType: t3.large
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true

Alternatively can used below command for building EKS cluster ## Please comment below if running cluster.yaml

 eksctl create cluster \
--name eks-cluster \
--version 1.17 \
--region eu-west-1 \
--nodegroup-name ng-worker \
--node-type t3.large \
--nodes 2 \
--vpc-private-subnets subnet-0e2237277fdc6641f \
--vpc-private-subnets subnet-06364fe4153d1b22b \
--vpc-public-subnets subnet-0bfd63e6df03ddca1 \
--vpc-public-subnets subnet-0735cc35ff5b785f8
