kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysqlvol
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/pankajmotwani/kubernetes/mycool-kube-deploy/kube-APP/mysqlvol"
